name: Build

on:
    push:
        branches: [ "master" ]

jobs:
    build:
        runs-on: [self-hosted, Linux, X64]
        environment: production

        steps:
            - name: Change permissions
              run: sudo chmod -R 777 ./

            - name: Checkout branch
              uses: actions/checkout@v4

            - name: Copy .env file to server
              run: |
                  cat << 'EOF' > .env
                  ${{ secrets.ENV_FILE }}
                  EOF

            - name: Start application
              run: |
                  sudo docker compose up -d --build